### ISSUE TITLE
Is there a way to use different config files?

### ISSUE THREAD

**Issue by elebetsamer** [feedhenry/fh-js-sdk#143]
For example, we are building an admin app for our services hosted in Feed Henry, and we want to enable the users to toggle between the different environments we have set up on the Feed Henry side of things. So, we have fhconfig-dev.json, fhconfig-stage.json and fhconfig-production.json. Is there any way we can init the fh library using one of those files? And then maybe also have a way to re-init with a different file at runtime? That way the user can pick their environment from a drop down and then view the data from that environment, all dynamically within the same page. Is this possible? If not, can it be added in as a feature?

**Comment by wei-lee** [comment]
@elebetsamer unfortunately, this is not supported at the moment. This is not how environments on our platform are designed for. The environments should be isolated from each other and the same client app should not be talking to multiple environments at the same time. It is possible to change the environment the client app should be connected to via updating [connections](http://docs.feedhenry.com/v3/product_features/projects.html#projects-connections). However, it is not possible to do it from within the client app programmatically.

Can I ask why your app needs to talk to multiple environments at the same time?

**Comment by elebetsamer** [comment]
The need is that we have built an admin application to manage data we are storing in Feed Henry services. In those services we have different environments and connection tags etc. So we need a way to allow our users to manage data in all of those different environments. Our admin app is built with Angular js, so we would like a way to dynamically switch which fhconfig file we are using when the user selects to change the environment they are trying to manage the data for.

**Comment by camilamacedo86** [comment]
Hi @elebetsamer,

Each environment is destinated for some action. For example, the DEV is for you use when you are developing your application, the UAT or TEST can be used for you test your application before it is published in production and the LIVE or PROD should be used for production applications. 

Also, you can connect your client application to a cloud application and this cloud application can be connected to N services and each service has your own database for example. I hope that this information helps you, however, the best place to address your doubts is via a support case if you still needing some help with it. Please, feel free to contact us via de this channel. We will be glad in be helpful. 

We are closing this since it is more a question than an issue in the project.
